[package]
name = "logic_sim"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
derive_more = "0.99.17"
enum-as-inner = "0.5.1"
num = "0.4.0"
raylib = "3.7.0"
lerp = "0.4.0"
